### ISSUE TITLE
Returned body contains html entities

### ISSUE THREAD

**Issue by jacargentina** [mpneuried/html-extractor#1]
The docs for using the library say **just the text**: so html entities should not be there on the returned body?

**Comment by mpneuried** [comment]
Hi, 
this module should strip all the html out and return only the metadata and content.

I updated the module and added check within the tests script, but i cannot detect a bug.
[See v0.1.4](https://github.com/mpneuried/html-extractor/releases/tag/0.1.4)

Can you provide me an example so i can reproduce your case?

**Comment by jacargentina** [comment]
I think it was a malformed html which caused this. Now i cant see any garbled text and i remember other module bug caused the wrong html. Closing.

**Comment by jacargentina** [comment]
Tell me if this is correct to show it, or my use is wrong (using current master):

**FILE** test.js

``` javascript
var e = require('html-extractor');
var m = new e();
m.extract('<body><p>&nbsp;HELLO!&nbsp;</p></body>', (err,data) => { console.log(err, data); } );
```

**OUTPUT**

```
null { meta: { title: '', description: '', keywords: [] },
  body: '&nbsp;HELLO!&nbsp;',
  h1: [] 
```

**Comment by jacargentina** [comment]
Think i've found it: may be there is a missing 

``` javascript
  { decodeEntities: true} 
```

for the htmlparser2 options?

**Comment by mpneuried** [comment]
I added your mentioned htmlparser2 option and optimized the trimming.
So now your `body` should be "HELLO!".
