### ISSUE TITLE
Reduce to many elements?

### ISSUE THREAD

**Issue by jacargentina** [mpneuried/html-extractor#2]
Currently, AFAIK, it is not possible to reduce a given HTML page to "many" elements, but only one.

In my case, i' m _tagging_ the elements i need, to later extract for indexing for a local site search engine. Until today i had just one element with the `id=indexable`. But today i need to tag two sections on the same html page, and index just those two.

Any chance to rework the extractor to return an array of matches instead of just one?

PS: maybe if that is possible, the `id=indexable` should be changed to `class=indexable` to better follow HTML standard

**Comment by mpneuried** [comment]
Hi,

with version `0.2.0` i a added the option `reduce.list` to be able to return a array of all reduced blocks.

Please test it and let me know if it works for you ;-)
